In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('./Img_index/train/progan_train.csv', index_col = 0)
df

                            label
file
airplane/0_real/00000.png     0.0
airplane/0_real/00001.png     0.0
airplane/0_real/00002.png     0.0
airplane/0_real/00004.png     0.0
airplane/0_real/00006.png     0.0
...                           ...
tvmonitor/1_fake/19995.png    1.0
tvmonitor/1_fake/19996.png    1.0
tvmonitor/1_fake/19997.png    1.0
tvmonitor/1_fake/19998.png    1.0
tvmonitor/1_fake/19999.png    1.0

[720119 rows x 1 columns]

In [5]:
df = df.filter(regex = 'airplane|cow', axis = 0)
df

                           label
file
airplane/0_real/00000.png    0.0
airplane/0_real/00001.png    0.0
airplane/0_real/00002.png    0.0
airplane/0_real/00004.png    0.0
airplane/0_real/00006.png    0.0
...                          ...
cow/1_fake/19995.png         1.0
cow/1_fake/19996.png         1.0
cow/1_fake/19997.png         1.0
cow/1_fake/19998.png         1.0
cow/1_fake/19999.png         1.0

[72012 rows x 1 columns]

In [6]:
df.to_csv('./Img_index/train/2class.csv', index=True)